package com.fpb.vault.vault

import com.fpb.vault.model.NotePayload
import com.fpb.vault.model.NoteType
import java.time.Instant
import java.time.ZoneId
import java.time.format.DateTimeFormatter
import java.util.Locale

/**
 * 图库导入产生的"照片记录"的命名与空壳判定。
 *
 * ## 用户报的现象
 *
 * > 在图库增加照片会自动创建照片列表，但是删除照片却没有同步删列表；
 * > 只要列表内容里的照片被全部删除，也应该把列表删掉。
 *
 * ## 为什么原来没删掉
 *
 * [com.fpb.vault.ui.VaultAppState.removePhoto] 里的判据一直是对的：
 *
 * ```kotlin
 * val hollowedOut = remaining.isEmpty() && payload.body.isBlank() && payload.title.isBlank()
 * ```
 *
 * 问题的前一问：**标题永远不为空**。图库导入时会给记录填一个标题
 * `照片 · 9月15日 20:44`，于是 `title.isBlank()` 恒为 false，这个判据一次都没有成立过，
 * 记录就留在列表里成了一张"点开什么都没有"的空卡片。
 *
 * ## 两种修法，以及为什么选现在这种
 *
 * **甲：记一个"标题是自动生成的"标记**（比如复用 `flags` 字节的某一位）。
 * 缺点是要动加密载荷的编码，而且**已经导进去的老记录没有这一位**，
 * 老用户升级后照旧不生效 —— 等于只修了一半。
 *
 * **乙（采用）：自动标题根本不写进记录，改成显示时按创建时间派生。**
 * 于是"标题为空"天然就等于"用户没自己起过名字"，判据原样成立；
 * 更关键的是**老记录也一并被覆盖到**：见 [isAutoGeneratedTitle]，
 * 它还会认领旧版本写进记录里的那种标题。用户不必重新导入任何东西。
 *
 * 代价是搜索里少了那个标题串，所以 [TITLE_WORD] 单独作为检索词补回去
 * （见 [NotePayload.searchableText]）。
 */
object PhotoRecord {

    /**
     * 照片记录在搜索里的代表词。用户不会去搜"9月15日 20:44"，但会搜"照片"。
     *
     * 定义在 [NotePayload] 上、这里只是转出来：模型层的 [NotePayload.searchableText]
     * 也要用它，而 `model` 不该反过来依赖 `vault`。
     */
    const val TITLE_WORD = NotePayload.IMAGE_TITLE_WORD

    /**
     * 派生的显示标题，例如 `照片 · 9月15日 20:44`。
     *
     * 用 [DateTimeFormatter] 而不是 `SimpleDateFormat`：后者不是线程安全的，
     * 而这里会在列表渲染时被每一张照片各调用一次。
     *
     * 语言固定为 [Locale.CHINA]：这是**为了与旧版本写进记录里的那个标题逐字符一致**
     * （旧代码用的就是 `SimpleDateFormat(…, Locale.CHINA)`），见 [isAutoGeneratedTitle]。
     * 跟着系统语言走的话，同一个时刻会派生出不同的串，老记录就认不出来了。
     */
    fun autoTitle(millis: Long, zone: ZoneId = ZoneId.systemDefault()): String =
        "$TITLE_WORD · " + TITLE_FORMAT.withZone(zone).format(Instant.ofEpochMilli(millis))

    /**
     * 这个标题是不是本应用自动生成的。
     *
     * 判据是"与该记录自己的创建时间格式化出来的一模一样" —— 带上时间戳比对，
     * 是为了把误判压到不可能：用户得正好手动敲出 `照片 · 9月15日 20:44`
     * 这么一个与他创建这条记录的时刻分秒不差的标题，才可能被认成自动标题。
     *
     * 时区变化会让比对落空，那是**安全方向**的落空：认不出来就保留记录，不会误删。
     */
    fun isAutoGeneratedTitle(
        title: String,
        createdAt: Long,
        zone: ZoneId = ZoneId.systemDefault(),
    ): Boolean {
        if (createdAt <= 0L) return false
        return title == autoTitle(createdAt, zone)
    }

    /**
     * 这条记录是不是"仅仅用来装这些照片"的空壳 —— 即用户**没有在上面留下任何自己的东西**。
     *
     * 任何一样用户自己写的或标的东西（标题、备注、标签、收藏）都会让它返回 false，
     * 于是记录被保留：照片删光了，备注还在，那它就不再只是照片的容器了。
     *
     * 判定只在"照片已经被删光"之后才有意义，调用点也就只有一个（删照片时）。
     */
    fun isShell(payload: NotePayload, zone: ZoneId = ZoneId.systemDefault()): Boolean {
        if (payload.type != NoteType.IMAGE) return false
        if (payload.images.isNotEmpty()) return false
        if (payload.body.isNotBlank()) return false
        if (payload.tags.isNotEmpty()) return false
        if (payload.favorite) return false
        // 标题为空 = 新版本导入的记录（自动标题不落盘）；
        // 与创建时间对得上 = 旧版本导入的记录（当时把标题写进去了）。
        return payload.title.isBlank() || isAutoGeneratedTitle(payload.title, payload.createdAt, zone)
    }

    private val TITLE_FORMAT: DateTimeFormatter =
        DateTimeFormatter.ofPattern("M月d日 HH:mm", Locale.CHINA)
}
