package com.fpb.vault.vault

import com.fpb.vault.model.ImageRef
import com.fpb.vault.model.NotePayload
import com.fpb.vault.model.NoteType
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import java.util.TimeZone
import java.time.ZoneId

/**
 * [PhotoRecord] 的守护测试。
 *
 * 这个类承载了用户报的第 2 条需求（"照片删光了列表还留着"）的全部判据，
 * 而它的正确性**完全靠两条容易在日后被改坏的约定**：
 *
 * 1. 派生标题的格式必须与**旧版本写进记录里的那种标题逐字符一致** ——
 *    否则老用户升级后，那些已经落盘的老标题就认不出来，记录照旧删不掉，
 *    等于只修了一半。这一条在 [派生标题与旧版本记录里的标题逐字符一致] 里被钉死。
 * 2. 只要用户自己写过一点点东西（标题/备注/标签/收藏），记录就必须无条件保留 ——
 *    这是用户明确选的那一项，宁可留着一张空卡片，也不能删掉用户写过的东西。
 */
class PhotoRecordTest {

    // ==================== 派生标题 ====================

    @Test
    fun `派生标题的形状是 照片 加 月日时分`() {
        val title = PhotoRecord.autoTitle(SAMPLE_MILLIS, ZONE)

        assertEquals("照片 · 9月16日 13:20", title)
    }

    @Test
    fun `派生标题与旧版本真机上落盘的标题一字不差`() {
        // 基准不是"我以为旧版是怎么写的"，而是两个**已经出货的版本在真机上的截图**：
        //   dist/evidence/v103/07-07-主页-照片记录可见.png   → 照片 · 9月15日 09:10
        //   dist/evidence/upgrade-v107/03-verify-03-过期催促条.png → 照片 · 9月16日 04:58
        //
        // 注意小时是**零填充**的（09:10 / 04:58 而不是 9:10 / 4:58）。
        // 这一点差一个字符，所有老记录就集体认不出来，用户升级后照旧删不掉空记录。
        assertEquals(LEGACY_V103_TITLE, PhotoRecord.autoTitle(LEGACY_V103_MILLIS, ZONE))
        assertEquals(LEGACY_V107_TITLE, PhotoRecord.autoTitle(LEGACY_V107_MILLIS, ZONE))
    }

    @Test
    fun `格式与旧版本的 SimpleDateFormat 写法等价`() {
        // 上面那条钉的是"结果"，这条钉的是"手法"：旧代码用的是 SimpleDateFormat，
        // 换成 DateTimeFormatter 之后必须逐字符等价 —— 包括零填充与数字宽度
        // （`M`/`d` 一位数不补零、`HH` 补到两位）。
        val legacy = "照片 · " + SimpleDateFormat(LEGACY_PATTERN, Locale.CHINA)
            .apply { timeZone = TimeZone.getTimeZone(ZONE) }
            .format(Date(SAMPLE_MILLIS))

        assertEquals(legacy, PhotoRecord.autoTitle(SAMPLE_MILLIS, ZONE))
    }

    @Test
    fun `不随系统默认语言漂移`() {
        // Locale 固定为 CHINA 是刻意的：跟着系统语言走的话，
        // 同一个时刻在不同手机上会派生出不同的串，老记录就认不出来了。
        val original = Locale.getDefault()
        try {
            Locale.setDefault(Locale.US)
            val inUs = PhotoRecord.autoTitle(SAMPLE_MILLIS, ZONE)
            Locale.setDefault(Locale.JAPAN)
            val inJapan = PhotoRecord.autoTitle(SAMPLE_MILLIS, ZONE)

            assertEquals("照片 · 9月16日 13:20", inUs)
            assertEquals("照片 · 9月16日 13:20", inJapan)
        } finally {
            Locale.setDefault(original)
        }
    }

    // ==================== 认领自动标题 ====================

    @Test
    fun `认自己派生的标题`() {
        assertTrue(
            PhotoRecord.isAutoGeneratedTitle(
                PhotoRecord.autoTitle(SAMPLE_MILLIS, ZONE),
                SAMPLE_MILLIS,
                ZONE,
            ),
        )
    }

    @Test
    fun `认旧版本落盘的那种标题`() {
        // 老用户不必重新导入任何东西，靠的就是这一条：
        // 这两个串是旧版本真机上截图里的原文（见上面那条测试的注释）。
        assertTrue(PhotoRecord.isAutoGeneratedTitle(LEGACY_V107_TITLE, LEGACY_V107_MILLIS, ZONE))
        assertTrue(PhotoRecord.isAutoGeneratedTitle(LEGACY_V103_TITLE, LEGACY_V103_MILLIS, ZONE))
    }

    @Test
    fun `用户手写的标题一律不认`() {
        listOf(
            "海边日落",
            "照片",                       // 只有词，缺时间
            "照片 · 9月16日 13:21",        // 时间差一分钟
            "我的照片 · 9月16日 13:20",    // 前面多了两个字
        ).forEach { written ->
            assertFalse(
                "「$written」是用户自己写的，不能被当成自动标题",
                PhotoRecord.isAutoGeneratedTitle(written, SAMPLE_MILLIS, ZONE),
            )
        }
    }

    @Test
    fun `创建时间缺失时不认`() {
        assertFalse(
            PhotoRecord.isAutoGeneratedTitle("照片 · 9月16日 13:20", 0L, ZONE),
        )
    }

    @Test
    fun `时区变化导致认不出来时偏向保留记录`() {
        // 在另一个时区里格式化，串自然对不上。这属于**安全方向**的落空：
        // 认不出来 → isShell 为 false → 记录被保留，绝不会误删用户的东西。
        val otherZone = ZoneId.of("America/New_York")
        val titleInOtherZone = PhotoRecord.autoTitle(SAMPLE_MILLIS, otherZone)

        assertFalse(
            PhotoRecord.isAutoGeneratedTitle(titleInOtherZone, SAMPLE_MILLIS, ZONE),
        )
    }

    // ==================== 空壳判定 ====================

    @Test
    fun `照片删光且标题为空时是空壳`() {
        // 新版本导入的记录就长这样：自动标题不落盘，所以 title 是空的。
        assertTrue(PhotoRecord.isShell(photoNote(title = "", images = emptyList()), ZONE))
    }

    @Test
    fun `照片删光但标题是旧版本落盘的自动标题时也是空壳`() {
        assertTrue(
            "老用户升级后不必重新导入，靠的就是这一条",
            PhotoRecord.isShell(
                photoNote(
                    title = LEGACY_V107_TITLE,
                    images = emptyList(),
                    createdAt = LEGACY_V107_MILLIS,
                ),
                ZONE,
            ),
        )
    }

    @Test
    fun `还剩照片就不是空壳`() {
        assertFalse(
            PhotoRecord.isShell(photoNote(title = "", images = listOf(image("a"))), ZONE),
        )
    }

    @Test
    fun `有备注就保留`() {
        assertFalse(
            PhotoRecord.isShell(
                photoNote(title = "", body = "这是去年在海边拍的", images = emptyList()),
                ZONE,
            ),
        )
    }

    @Test
    fun `有标签就保留`() {
        assertFalse(
            PhotoRecord.isShell(
                photoNote(title = "", tags = listOf("旅行"), images = emptyList()),
                ZONE,
            ),
        )
    }

    @Test
    fun `收藏了就保留`() {
        assertFalse(
            PhotoRecord.isShell(
                photoNote(title = "", favorite = true, images = emptyList()),
                ZONE,
            ),
        )
    }

    @Test
    fun `用户手写过标题就保留`() {
        // 用户明确选的那一项：只要他在上面留过自己的东西，照片删光了也留着这条记录。
        assertFalse(
            PhotoRecord.isShell(photoNote(title = "海边日落", images = emptyList()), ZONE),
        )
    }

    @Test
    fun `只留空白的备注不算用户写过东西`() {
        assertTrue(
            PhotoRecord.isShell(photoNote(title = "", body = "   \n  ", images = emptyList()), ZONE),
        )
    }

    @Test
    fun `非图片记录永远不是空壳`() {
        val text = NotePayload(
            type = NoteType.TEXT,
            title = "",
            body = "普通笔记",
            createdAt = SAMPLE_MILLIS,
            updatedAt = SAMPLE_MILLIS,
        )

        assertFalse(
            "这条判据只在删照片时用；别的类型不该被它误伤",
            PhotoRecord.isShell(text, ZONE),
        )
    }

    // ==================== 与搜索的联动 ====================

    @Test
    fun `照片记录仍能被 照片 这个词搜到`() {
        // 自动标题不落盘的直接代价：搜索里少了那个串。
        // searchableText 单独把"照片"补回去，否则"搜照片"会搜不到任何东西。
        val payload = photoNote(title = "", images = listOf(image("a")))

        assertTrue(payload.searchableText().contains("照片"))
    }

    @Test
    fun `用户自己起了名字时搜索里不会多出 照片 这个词`() {
        val payload = photoNote(title = "海边日落", images = listOf(image("a")))

        assertFalse(
            "用户给记录起了名字，就该按他的名字搜，不该再挂一个通用词",
            payload.searchableText().contains("照片"),
        )
        assertTrue(payload.searchableText().contains("海边日落"))
    }

    @Test
    fun `检索词常量在模型层与图库层是同一个`() {
        assertEquals(NotePayload.IMAGE_TITLE_WORD, PhotoRecord.TITLE_WORD)
    }

    // ==================== 构造测试数据 ====================

    /** 2025-09-16 13:20:00 +08:00 */
    private val SAMPLE_MILLIS = 1_758_000_000_000L
    private val ZONE: ZoneId = ZoneId.of("Asia/Shanghai")

    /**
     * 旧版本真机上截图里读出来的标题原文，以及它们各自对应的创建时刻。
     *
     * 之所以用**毫秒值**而不是把标题串拼出来当基准：截图里只有到分钟的精度，
     * 而这一分钟里的任意一秒格式化出来都是同一个串，所以取该分钟内的中段即可。
     */
    private val LEGACY_V103_MILLIS = 1_757_898_630_000L // 2025-09-15 09:10:30 +08:00
    private val LEGACY_V103_TITLE = "照片 · 9月15日 09:10"
    private val LEGACY_V107_MILLIS = 1_757_969_910_000L // 2025-09-16 04:58:30 +08:00
    private val LEGACY_V107_TITLE = "照片 · 9月16日 04:58"

    /** 旧版本写标题用的就是这个模式。 */
    private val LEGACY_PATTERN = "M月d日 HH:mm"

    private fun image(blobId: String) = ImageRef(blobId = blobId, width = 100, height = 100)

    private fun photoNote(
        title: String,
        body: String = "",
        tags: List<String> = emptyList(),
        favorite: Boolean = false,
        images: List<ImageRef>,
        createdAt: Long = SAMPLE_MILLIS,
    ) = NotePayload(
        type = NoteType.IMAGE,
        title = title,
        body = body,
        tags = tags,
        createdAt = createdAt,
        updatedAt = createdAt,
        favorite = favorite,
        images = images,
    )
}
